app1/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static

from app1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('articles.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from articles import views

app_name='articles'

urlpatterns = [
    path('search/', views.CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='index'),
    path('news/<slug:article_slug>/', views.ArticleView.as_view(), name='article'),
    path('news/<slug:article_slug>/like/', views.AddLikeView.as_view(), name='liked'),
    path('news/<slug:article_slug>/comment/', views.AddCommentView.as_view(), name='commented'),
]

articles/models.py
from django.db import models
from django.urls import reverse

from users.models import User


class Category(models.Model):
    name = models.CharField(verbose_name='Название',
                            max_length=128, unique=True)
    slug = models.SlugField(verbose_name='URL', max_length=128, unique=True,
                            blank=True, null=True)

    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:index', kwargs={"category_slug": self.slug})


class ArticleManager(models.Manager):
    def counts_reactions(self, articles):
        """Возвращает QuerySet статей с аннотациями кол-ва реакций"""
        return self.filter(pk__in=articles).annotate(
            count_likes_on_article=models.Count('likes', distinct=True),
            count_comments_on_article=models.Count('comments', distinct=True))


class Article(models.Model):
    title = models.CharField(verbose_name='Название', max_length=128,
                             unique=True)
    slug = models.SlugField(verbose_name='URL', max_length=128, unique=True,
                            blank=True, null=True)
    summary = models.TextField(verbose_name='Описание', blank=True, null=True)
    description = models.TextField(verbose_name='Текст статьи', blank=True,
                                   null=True)
    category = models.ForeignKey(to=Category, on_delete=models.SET_NULL,
                                 related_name='articles', null=True,
                                 verbose_name='Категория')
    image = models.ImageField(verbose_name='Изображение',
                              upload_to='articles_images', blank=True, null=True)
    date_creation = models.DateTimeField(verbose_name='Дата создания',
                                         auto_now_add=True)
    date_update = models.DateTimeField(verbose_name='Дата обновления',
                                       auto_now=True)

    objects = ArticleManager()

    class Meta:
        db_table = 'article'
        verbose_name = 'Статью'
        verbose_name_plural = 'Статьи'
        ordering = ('-date_creation',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:article', kwargs={"article_slug": self.slug})


class LikeManager(models.Manager):
    def create_like(self, request, article):
        """Создание лайка на статье"""
        return self.create(user=request.user if request.user.is_authenticated else None,
                    session_key=request.session.session_key if not
                    request.user.is_authenticated else None,
                    article=article)
    
    def liked_articles(self, request, articles):
        """Возвращает ValuesQuerySet (pk) статей, которые лайкал пользователь"""
        if request.user.is_authenticated:
            query_kwargs = {"user": request.user}
        # Если пользователь не авторизован, создаем ему сессионный ключ
        elif not request.session.session_key:
            request.session.create()
            query_kwargs = {"session_key": request.session.session_key}
        else:
            query_kwargs = {"session_key": request.session.session_key}
        return self.filter(article__in=articles, **query_kwargs)\
                   .values_list('article', flat=True)


class Like(models.Model):
    article = models.ForeignKey(to=Article, on_delete=models.CASCADE,
                                related_name='likes', verbose_name='Новость')
    user = models.ForeignKey(to=User, on_delete=models.SET_NULL,
                             related_name='likes', verbose_name='Пользователь',
                             blank=True, null=True)
    session_key = models.CharField(verbose_name='Сессионный ключ', max_length=32,
                                   blank=True, null=True)
    created_timestamp = models.DateTimeField(verbose_name='Дата добавления',
                                             auto_now_add=True)

    objects = LikeManager()

    class Meta:
        db_table = 'like'
        verbose_name = 'Лайк'
        verbose_name_plural = 'Лайки'

    def __str__(self):
        if self.user:
            return f'{self.article} - {self.user}'
        return f'{self.article} - Аноним'


class Comment(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_NULL,
                             related_name='comments', verbose_name='Автор',
                             blank=True, null=True)
    text_comment = models.TextField(verbose_name='Комментарий', max_length=500)
    parent = models.ForeignKey(to='self', on_delete=models.CASCADE,
                               related_name='children', blank=True, null=True,
                               verbose_name='Родительский комментарий')
    article = models.ForeignKey(to=Article, on_delete=models.CASCADE,
                                related_name='comments', verbose_name='Статья')
    created_timestamp = models.DateTimeField(verbose_name='Дата добавления',
                                             auto_now_add=True)

    class Meta:
        db_table = 'comment'
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        if self.user:
            return f'{self.user} - {self.article}'
        return f'Неизвестный - {self.article}'

articles/forms.py
from django import forms

from articles.models import Comment


class CommentsForm(forms.ModelForm):
    text_comment = forms.CharField(label='Ваш комментарий*',
                                   max_length=500,
                                   widget=forms.Textarea(
                                       attrs={'class': 'form-control',
                                              'placeholder': 'Введите текст комментария',
                                              'rows': '5'}))

    class Meta:
        model = Comment
        fields = ('text_comment',)

articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormMixin

from articles.forms import CommentsForm
from articles.mixins import ReactionMixin
from articles.models import Article, Like
from articles.utils import q_search


class CatalogView(ReactionMixin, ListView):
    model = Article
    template_name = 'articles/catalog.html'
    context_object_name = 'articles'
    paginate_by = 4

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        sort = self.request.GET.get('sort')
        query = self.request.GET.get('q')

        if category_slug == 'all':
            articles = super().get_queryset()
        elif query:
            articles = q_search(query)
        else:
            articles = super().get_queryset().\
                               filter(category__slug=category_slug)

        if sort:
            articles = articles.order_by(sort)

        return articles

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Каталог'
        context['slug_url'] = self.kwargs.get('category_slug')
        return self.get_mixin_context(context)


class ArticleView(FormMixin, ReactionMixin, DetailView):
    template_name = 'articles/news.html'
    slug_url_kwarg = 'article_slug'
    context_object_name = 'article'
    form_class = CommentsForm

    def get_initial(self):
        initial = super().get_initial()
        if self.request.user.is_authenticated:
            initial['username'] = self.request.user.username
            initial['email'] = self.request.user.email
        return initial

    def get_object(self, queryset=None):
        news = Article.objects.get(slug=self.kwargs.get(self.slug_url_kwarg))
        return news

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        return self.get_mixin_context(context)


class AddCommentView(LoginRequiredMixin, ArticleView):
    def get_success_url(self, **kwargs):
        return reverse_lazy('catalog:article', kwargs={'article_slug':
                                                       self.get_object().slug})

    def post(self, request, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return super().form_invalid(form)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.article = self.get_object()
        if form.data['comment_parent']:
            self.object.parent_id = int(form.data['comment_parent'])
        self.object.save()
        messages.success(self.request, f'{self.request.user.username},\
                                         Ваш комментарий успешно добавлен!')
        return super().form_valid(form)


class AddLikeView(ReactionMixin, View):
    def post(self, request, **kwargs):
        article_id = request.POST.get('article_id')
        article = Article.objects.get(pk=article_id)
        like = self.get_like(request, article)

        if not like.exists():
            Like.objects.create_like(request, article)
            message = 'Лайк добавлен'
        else:
            like.delete()
            message = 'Лайк убран'

        like_items_html = render_to_string(
            "articles/includes/included_reactions.html",
            {"article": article},
            request=request
        )

        response_data = {
            "message": message,
            "like_items_html": like_items_html,
        }
        return JsonResponse(response_data)

articles/templates/articles/catalog.html
{% extends "base.html" %}
{% load static %}
{% load articles_tags %}


{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
<div class="row">
    <div class="col-md-12 dropdown mb-2">
        <button class="btn btn-secondary dropdown-toggle btn-dark" type="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Фильтры
        </button>

        <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url "catalog:index" slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="checkbox" name="popular" id="flexCheckDefault" value="on" {% if request.GET.popular == 'on' %}checked{% endif %}>
                {% if request.GET.q %}
                    <input type="hidden" name="q" value="{{ request.GET.q }}">
                {% endif %}
                <label class="form-check-label" for="flexCheckDefault">Популярные</label>
            </div>
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="sort" id="flexRadioDefault1" value="-date_creation" {% if not request.GET.sort or request.GET.sort == '-date_creation' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault1">От новых к старым</label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="sort" id="flexRadioDefault2" value="date_creation" {% if request.GET.sort == 'date_creation' %}checked{% endif %}>
                <label class="form-check-label" for="flexRadioDefault2">От старых к новым</label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
    </div>

    {% if request.GET.q %}
        <h3 class="mt-4 searh-article">Результаты поиска по запросу "{{ request.GET.q }}"</h3>
        {% if not articles %}
            <h2 class="mt-4 searh-article">По запросу ничего не найдено</h2>
        {% endif %}
    {% endif %}

    {% if request.GET.popular and not articles %}
        <h1 class="mt-4 searh-article">Популярных статей не найдено</h1>
    {% endif %}

    {% for article in articles %}
        <div class="col-lg-6 col-md-12 p-4">
            <div class="card mb-2 w-100">
                <div class="card-header">
                    <h6 class="card-title">
                        <a class="text-muted text-uppercase" data-toggle="collapse" href="{{ article.get_absolute_url }}">
                            <b>{{ article.title }}</b>
                        </a>
                    </h6>
                </div>
                <div class="collapse show">
                    <img src="{{ article.image.url }}" class="card-img-top" alt="{{ article.title }}">
                    <div class="card-body text-truncate">{{ article.summary }}</div>
                    <div class="card-footer bg-transparent d-sm-flex align-items-sm-center border-top-0 pt-0">
                        <span class="text-muted">Дата публикации: {{ article.date_creation }}</span>
                        {% include "articles/includes/included_reactions.html" %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% if articles %}
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center my-4">
        <div class="custom-shadow d-flex">
            <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number %}{% else %}#{% endif %}">Предыдущая</a>
            </li>
            {% for page in page_obj.paginator.page_range %}
                {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                    <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                        <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                    </li>
                {% endif %}
            {% endfor %}
            <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number %}{% else %}#{% endif %}">Следующая</a>
            </li>
        </div>
    </ul>
</nav>
{% endif %}
{% endblock content %}


{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; MyBlog 2025</p>
        </div>
    </footer>
{% endblock footer %}

articles/templates/articles/news.html
{% extends "base.html" %}
{% load static %}
{% load articles_tags %}


{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
<div class="row">
    <div class="col-lg-12 col-md-12 p-4">
        <div class="container">
            <div class="card mb-2 w-100">
                <div class="card-header">
                    <h6 class="card-title">
                        <a class="text-uppercase" data-toggle="collapse">
                            <b>{{ article.title }}</b>
                        </a>
                    </h6>
                </div>
                <div id="{{ article.id }}" class="collapse show">
                    <img class="image" src="{{ article.image.url }}" alt="{{ article.title }}">
                    <div class="card-body" id="text-news">
                        <p>{{ article.description | linebreaks}}</p>
                    </div>
                    <div
                        class="card-footer bg-transparent d-sm-flex align-items-sm-center border-top-0 pt-0">
                        <span class="text-muted">Создан: {{ article.date_creation }} | Обновлен: {{ article.date_update }} </span>
                        {% include "articles/includes/included_reactions.html" %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-12">
        <div class="container" id="form-comments">
            <div class="bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="editContent">Оставить комментарий</h3>
                {% if not user.is_authenticated %}
                    <h6 class="editContent">(оставлять комментарии могут только авторизованные пользователи)</h6>
                {% endif %}
                <form action="{% url "catalog:commented" article.slug %}" method="post" class="mt-4">
                    <div class="row my-4">
                        {% csrf_token %}
                        <input type="hidden" name="comment_parent" id="id_comment_parent" value="">
                        {% for field in form %}
                        <div class="col-lg-12 form-group">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ field.errors }}</div>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    <button type="submit" class="mt-1 btn btn-success py-3">Отправить</button>
                </form>
            </div>
        </div>
    </div>

    {% tag_comments article as comments %}
    <div class="col-lg-12" id="block-comments">
        <div class="container">
            <div class="bg-white p-3 mb-4 mx-2 custom-shadow">
                <h3>Комментарии <b class="count-comments">{{ article.count_comments_on_article }}</b></h3>
            </div>
            {% for comment in comments %}
                <div class="media bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    {% if comment.user.image %}
                        <img src="{{ comment.user.image.url }}" class="img-fluid rounded-circle" alt="Аватар пользователя" style="max-width:50px; height:auto;">
                    {% else %}
                        <img src="{% static "deps/images/avatar.png" %}" class="mr-3" alt="Аватар пользователя">
                    {% endif %}
                    <div class="media-body mt-2">
                        <h5 class="user-comment">{{ comment.user }}</h5>
                        <p class="text-comment">{{ comment.text_comment }}</p>
                        <p class="date-comment text-muted">Дата создания: {{ comment.created_timestamp }}
                            <a class="mx-5 reply-comment" href="#form-comments" onclick="addComment('{{ comment.user }}', '{{ comment.id }}')">Ответить</a>
                        </p>
                        {% include 'articles/includes/comments_children.html' with comments=comment.nested_children %}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; MyBlog 2025</p>
        </div>
    </footer>
{% endblock footer %}