app1/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static

from app1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('articles.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name='users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    image = models.ImageField(verbose_name='Аватар', upload_to='users_images',
                              blank=True, null=True)

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django.contrib.auth.forms import (AuthenticationForm, UserCreationForm, 
                                       UserChangeForm)
from django import forms

from users.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(
                                   attrs={'autofocus': True,
                                          'class': 'form-control',
                                          'placeholder': 'Введите имя пользователя'}))
    password = forms.CharField(label='Пароль',
                               strip=False,
                               widget=forms.PasswordInput(
                                   attrs={'autocomplete': 'current-password',
                                          'class': 'form-control',
                                          'placeholder': 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(label='Имя*',
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control',
                                            'placeholder': 'Введите имя'}))
    last_name = forms.CharField(label='Фамилия*',
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control',
                                           'placeholder': 'Введите фамилию'}))
    username = forms.CharField(label='Имя пользователя*',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(label='Email*',
                            widget=forms.EmailInput(
                                attrs={'class': 'form-control',
                                       'placeholder': 'Введите email *youremail@example.com'}))
    password1 = forms.CharField(label='Пароль*',
                                strip=False,
                                widget=forms.PasswordInput(
                                    attrs={'autocomplete': 'current-password',
                                           'class': 'form-control',
                                           'placeholder': 'Введите пароль'}))
    password2 = forms.CharField(label='Подтверждение пароля*',
                                strip=False,
                                widget=forms.PasswordInput(
                                    attrs={'autocomplete': 'current-password',
                                           'class': 'form-control',
                                           'placeholder': 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2"
        )


class UserProfileForm(UserChangeForm):
    image = forms.ImageField(required=False,
                             widget=forms.FileInput(
                                 attrs={'class': 'form-control mt-3',
                                        'accept': 'image/*'}))
    first_name = forms.CharField(label='Имя',
                                 widget=forms.TextInput(
                                     attrs={'class': 'form-control',
                                            'placeholder': 'Введите имя'}))
    last_name = forms.CharField(label='Фамилия',
                                widget=forms.TextInput(
                                    attrs={'class': 'form-control',
                                           'placeholder': 'Введите фамилию'}))
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Введите имя пользователя'}))
    email = forms.CharField(label='Email',
                            widget=forms.EmailInput(
                                attrs={'class': 'form-control',
                                       'placeholder': 'Введите email *youremail@example.com'}))

    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email'
        )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'password' in self.fields:
            del self.fields['password']

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.contrib import auth, messages
from django.db.models import Count
from django.views.generic import CreateView, UpdateView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy

from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm
from articles.models import Like


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def get_success_url(self):
        redirect_page = self.request.POST.get('next')
        if redirect_page and redirect_page != reverse('user:logout'):
            return redirect_page
        return reverse_lazy('main:index')

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.get_user()
        if user:
            auth.login(self.request, user)
            if session_key:
                # Добавляем пользователя на лайки, которые он поставил, являясь анонимом
                Like.objects.filter(session_key=session_key).update(user=user)
                # Получаем дубликаты, на которых пользователь уже ставил лайк
                duplicates = Like.objects.filter(user=user)\
                                         .values_list('article', flat=True)\
                                         .alias(duplicate=Count('article'))\
                                         .filter(duplicate__gt=1)
                if duplicates:
                    Like.objects.filter(article__in=duplicates,
                                        session_key=session_key).delete()
            messages.success(self.request,
                             f'{user.username}, Вы вошли в аккаунт!')
        return HttpResponseRedirect(self.get_success_url())
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context
    

class UserRegistrationView(CreateView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('user:profile')

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.instance
        if user:
            form.save()
            auth.login(self.request, user)
            if session_key:
                Like.objects.filter(session_key=session_key).update(user=user)
            messages.success(self.request,
                             f'{user.username}, Вы успешно зарегистрировалась!')
        return HttpResponseRedirect(self.success_url)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context


class UserProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/profile.html'
    form_class = UserProfileForm
    success_url = reverse_lazy('user:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Личный кабинет обновлен!')
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Личный кабинет'
        return context


@login_required
def logout(request):
    messages.success(request, f'{request.user.username}, Вы вышли из аккаунта!')
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 rounded custom-shadow">
                <h2 class="text-center mb-4">Авторизация</h2>
                <form action="{% url "user:login" %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                    {% for field in form %}
                        <div class="mb-3">
                            <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-dark btn-block">Войти</button>
                </form>
                <div class="mt-3">
                    <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration" %}">Создать аккаунт</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; MyBlog 2024</p>
        </div>
    </footer>
{% endblock footer %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
<div class="row">
    <div class="container mt-5 ">
        <div class="row ">
            <div class="col-lg-5 col-md-5">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Профиль пользователя</h3>
                    <form action="{% url "user:profile" %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            {% for field in form %}
                                {% if field.name == 'image' %}
                                    <div class="col-md-12 mb-3 text-center">
                                        {% if user.image %}
                                            <img src="{{ user.image.url }}" alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px;">
                                        {% else %}
                                            <img src="{% static "deps/images/baseavatar.jpg" %}" alt="Аватар пользователя" class="img-fluid rounded-circle" style="max-width: 150px;">
                                        {% endif %}
                                        {{ field }}
                                        {% if field.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ field.errors }}</div>
                                        {% endif %}
                                    </div>
                                {% else %}
                                    <div class="col-md-12 mb-3">
                                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                        {{ field }}
                                        {% if field.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ field.errors }}</div>
                                        {% endif %}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-dark">Сохранить</button>
                    </form>
                </div>
            </div>
            
            <div class="col-lg-7 col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Моя вовлеченность</h3>
                    <div class="container">
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading1">
                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse1" aria-expanded="false" aria-controls="collapse1">
                                        <strong>Отмеченные статьи</strong>
                                    </button>
                                </h2>
                                <div id="collapse1" class="accordion-collapse collapse show" aria-labelledby="heading1" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Название статьи</th>
                                                    <th>Дата публикации</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Из ядра ОС Android убрали поддержку интерактивной архитектуры RISC-V</a></td>
                                                    <td>15 апреля 2024</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading2">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse2" aria-expanded="false" aria-controls="collapse2">
                                        <strong>Прокомметированные статьи</strong>
                                    </button>
                                </h2>
                                <div id="collapse2" class="accordion-collapse collapse" aria-labelledby="heading2" data-bs-parent="#accordionExample">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                                <tr>
                                                    <th>Название статьи</th>
                                                    <th>Дата публикации</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td><a class="text-white" href="#">Из ядра ОС Android убрали поддержку интерактивной архитектуры RISC-V</a></td>
                                                    <td>15 апреля 2024</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; MyBlog 2024</p>
        </div>
    </footer>
{% endblock footer %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock css %}


{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Регистрация</h2>
                <form action="{% url "user:registration" %}" method="post">
                    <div class="row">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="col-md-6 mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field }}
                                {% if field.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ field.errors }}</div>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                    <button type="submit" class="btn btn-dark btn-block">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}


{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; MyBlog 2024</p>
        </div>
    </footer>
{% endblock footer %}