app1/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static

from app1 import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('articles.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/urls.py
from django.urls import path
from articles import views

app_name='articles'

urlpatterns = [
    path('search/', views.CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='index'),
    path('news/<slug:article_slug>/', views.ArticleView.as_view(), name='article'),
    path('news/<slug:article_slug>/like/', views.AddLikeView.as_view(), name='liked'),
    path('news/<slug:article_slug>/comment/', views.AddCommentView.as_view(), name='commented'),
]

main/urls.py
from django.urls import path
from main import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

users/urls.py
from django.urls import path

from users import views

app_name='users'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('registration/', views.UserRegistrationView.as_view(), name='registration'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
    path('logout/', views.logout, name='logout'),
]

templates/base.html
{% load static %}
{% load articles_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href= "{% static "deps/css/my_css.css" %}">
    {% block css %} {% endblock css %}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand text-white" href="{% url "main:index" %}">MyBlog</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item text-white" href="{% url "main:about" %}">О команде</a></li>
                            </ul>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link text-white" aria-current="page" href="{% url "user:login" %}">Войти</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Мой профиль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item text-white" href="{% url "user:profile" %}">Личный кабинет</a></li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li><a class="dropdown-item text-white" href="{% url "admin:index" %}">Админ-панель</a></li>
                                    {% endif %}
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item text-white" href="{% url "user:logout" %}">Выйти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                    <form action="{% url "catalog:search" %}" method="get" class="d-flex" role="search">
                        <input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Поиск">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <section>
        <div class="container">
            <div class="row mt-1 position-absolute z-3">
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16" height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_categories as categories %}
                        {% for category in categories %}
                            <li><a class="dropdown-item text-white" href="{{ category.get_absolute_url }}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2"></div>
                <div class="col-lg-10">
                    {% include "includes/notifications.html" %}
                    {% block content %}{% endblock content %}
                </div>
    </section>
    {% block footer %}{% endblock footer %}
    <script src="{% static "deps/js/jquery/jquery-3.7.1.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>
</html>